/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre;

import Gestion.Dossier;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Client;




/**
 *
 * @author RZR
 */
public class jFrame_auto_pressing extends javax.swing.JFrame {
     ImageIcon ic,ic2;
    Client c;
    Tache tache;
    int position,position2;
    Dossier file=new Dossier();
    DefaultTableModel model;
    /**
     * Creates new form jFrame_auto_pressing
     */
    public jFrame_auto_pressing() {
        initComponents();
         this.setResizable(false);
        this.setLocationRelativeTo(null);
         txtContact.setEnabled(false);
        charge();
        vision(true);
    }
    private void affichage(Client c){
      
        txtNom.setText(c.getNom());
        txtPrenom.setText(c.getPrenom());
        
         txtContact.setText(c.getContact());
        cboGenre.setSelectedItem(c.getGenre());
        ic = new ImageIcon();
        ic=c.getImage();
         lblImages.setIcon(ic);
        
        
        vision(false);
        
    }
     private void vider(){
       
        txtNom.setText("");
        txtPrenom.setText("");
       
         txtContact.setText("");
         ic = null;
          lblImages.setIcon(ic);
    }
  private void vision(boolean c) {
        BtnAjouter.setVisible(c);
        btnSearch.setVisible(c);
        btnEdit.setVisible(!c);
        btnDelete.setVisible(!c);
        btnCancel.setVisible(!c);
      }
    private void charge() {
        //creation du modele
        model = new DefaultTableModel();
        //ajout de colonnes au modele
        model.addColumn("NOM");
        model.addColumn("PRENOM");
	model.addColumn("CODE");
        model.addColumn("CONTACT");
        model.addColumn("GENRE");
        //definir le modele par rapport a la table
        List_enreg.setModel(model);
        for (Client c : file.client) {
            //creation d'un objet en ligne
            Object obj[] = {c.getNom(), c.getPrenom(),c.getCode(), c.getContact(),  c.getGenre()};
            model.addRow(obj);
        }
    }
     private String boite(int a){
        String c="";
            JFileChooser jc=new JFileChooser();
            int rep;
            if(a==0){
              rep=jc.showOpenDialog(this);
            }else{
                rep=jc.showSaveDialog(this);
            }
            if(rep==JFileChooser.APPROVE_OPTION){
             c=jc.getSelectedFile().getAbsolutePath();
            }
            
            return c;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbConct = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_enreg = new javax.swing.JTable();
        cboGenre = new javax.swing.JComboBox<>();
        lblImages = new javax.swing.JLabel();
        BtnAjouter = new javax.swing.JButton();
        txtCode1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        lblImage2 = new javax.swing.JLabel();
        btnSelcet2 = new javax.swing.JButton();
        cbo_vetement = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbo_mois = new javax.swing.JComboBox<>();
        cbo_jour1 = new javax.swing.JComboBox<>();
        cbo_jour2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbo_mois2 = new javax.swing.JComboBox<>();
        cbo_annee1 = new javax.swing.JComboBox<>();
        cbo_annee = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        List_enregL_R = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        List_enreg_rep = new javax.swing.JTable();
        btn_laver_repasser = new javax.swing.JButton();
        btnModif2 = new javax.swing.JButton();
        btnSupprimer2 = new javax.swing.JButton();
        btnAnnuler2 = new javax.swing.JButton();
        btnRepasser = new javax.swing.JButton();
        btnModifier3 = new javax.swing.JButton();
        btnSupprimer3 = new javax.swing.JButton();
        btnAnnuler3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(153, 153, 153));
        jInternalFrame1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        jInternalFrame1.setForeground(new java.awt.Color(51, 51, 51));
        jInternalFrame1.setTitle("ENREGISTREMENT DE LA CLIENTELLE");
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel1.setText("NOM:");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel2.setText("PRENOM(S):");

        lbConct.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        lbConct.setText("CONTACT:");

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel5.setText("GENRE:");

        btnSearch.setText("RECHERCHER");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEdit.setText("MODIFIER");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("SUPPRIMER");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("ANNULER");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSelect.setText("SELECT");
        btnSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectMouseClicked(evt);
            }
        });
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        List_enreg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        List_enreg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        List_enreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_enregMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(List_enreg);

        cboGenre.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        cboGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOMME", "FEMME" }));
        cboGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGenreActionPerformed(evt);
            }
        });

        lblImages.setBackground(new java.awt.Color(0, 0, 0));
        lblImages.setOpaque(true);
        lblImages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagesMouseClicked(evt);
            }
        });

        BtnAjouter.setText("ENREGISTRER");
        BtnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjouterActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel3.setText("CODE:");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(lbConct)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(cboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContact)
                            .addComponent(txtCode1))
                        .addGap(45, 45, 45)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImages, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 107, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(lblImages, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSelect))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbConct)
                                    .addComponent(txtCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(BtnAjouter)
                                    .addComponent(btnSearch))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame2.setBackground(new java.awt.Color(102, 102, 102));
        jInternalFrame2.setTitle("OPERATION A EFFECTUER");
        jInternalFrame2.setVisible(true);

        lblImage2.setBackground(new java.awt.Color(0, 0, 0));
        lblImage2.setOpaque(true);
        lblImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage2MouseClicked(evt);
            }
        });

        btnSelcet2.setText("\"SELECT\"");
        btnSelcet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelcet2ActionPerformed(evt);
            }
        });

        cbo_vetement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHEMISE: 150F", "CULOTTE: 100F", "DRAP: 500F", "JEANS: 300F", "JUPE: 150F", "NAPE DE TABLE: 500F", "PANTALON: 200F", "POLO: 300F", "PULL OVER: 500F", "RIDEAU: 1000F", "ROBE: 300F", "ROBE DE CEREMONI: 1000F", "ROBE DE MARIAGE: 2000F", "SERVIETTE: 300F", "T-SHIRT: 100F", "VESTE: 1500F" }));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        jLabel4.setText("TYPE DE VETEMENT");

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        jLabel6.setText("DATE D ENTREE");

        cbo_mois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANVIER", "FEVRIER", "MARS", "AVRIL", "MAIS", "JUIN", "JUILLET", "AOUT", "SEPTEMBRE", "OCTOBRE", "NOVEMBRE", "DECEMBRE" }));

        cbo_jour1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbo_jour2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbo_jour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_jour2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        jLabel7.setText("DATE RDV");

        cbo_mois2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANVIER", "FEVRIER", "MARS", "AVRIL", "MAIS", "JUIN", "JUILLET", "AOUT", "SEPTEMBRE", "OCTOBRE", "NOVEMBRE", "DECEMBRE" }));

        cbo_annee1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025" }));

        cbo_annee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025" }));

        List_enregL_R.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        List_enregL_R.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_enregL_RMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(List_enregL_R);

        List_enreg_rep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(List_enreg_rep);

        btn_laver_repasser.setText("LAVER+ REPASSER");

        btnModif2.setText("MODIFIER");

        btnSupprimer2.setText("SUPPRIMER");

        btnAnnuler2.setText("ANNULER");

        btnRepasser.setText("REPASSER SIMPLE");

        btnModifier3.setText("MODIFIER");

        btnSupprimer3.setText("SUPPRIMER");

        btnAnnuler3.setText("ANNULER");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSelcet2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblImage2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_laver_repasser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbo_jour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbo_jour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                                .addComponent(cbo_mois2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbo_annee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                                .addComponent(cbo_mois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbo_annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbo_vetement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                            .addComponent(btnModifier3)
                                            .addGap(35, 35, 35)
                                            .addComponent(btnSupprimer3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAnnuler3))
                                        .addComponent(btnRepasser, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(btnModif2)
                        .addGap(33, 33, 33)
                        .addComponent(btnSupprimer2)
                        .addGap(35, 35, 35)
                        .addComponent(btnAnnuler2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelcet2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbo_vetement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbo_mois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbo_annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbo_jour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbo_jour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_mois2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_annee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_laver_repasser)
                    .addComponent(btnRepasser))
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModif2)
                    .addComponent(btnSupprimer2)
                    .addComponent(btnAnnuler2)
                    .addComponent(btnModifier3)
                    .addComponent(btnSupprimer3)
                    .addComponent(btnAnnuler3))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInternalFrame1)
                    .addComponent(jInternalFrame2))
                .addGap(0, 52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjouterActionPerformed
        //recuperation des valeurs saisies
        String nom = txtNom.getText().trim();
        String prenoms = txtPrenom.getText().trim();
        String genre = cboGenre.getSelectedItem().toString();
        String contact= txtContact.getText().trim();
        //verifier si l'utilisateur a saisi des info
        if (nom.length() == 0) {
            JOptionPane.showMessageDialog(this, "VEUILLEZ SAISIR LE NOM SVP!", "ERROR", JOptionPane.ERROR_MESSAGE);
            //          recuperation du curseur
            txtNom.requestFocus();
        } else if (nom.length() == 0) {
            JOptionPane.showMessageDialog(this, "VEUILLEZ SAISIR LE PRENOM(S) SVP!", "ERROR", JOptionPane.ERROR_MESSAGE);
            //          recuperation du curseur
            txtPrenom.requestFocus();
        } else if (prenoms.length() == 0) {
            JOptionPane.showMessageDialog(this, "VEUILLEZ SAISIR LA DATE DE NAISSANCE SVP!", "ERROR", JOptionPane.ERROR_MESSAGE);

        } else {
            if (ic == null) {
                JOptionPane.showMessageDialog(this, "VEUILLEZ SELECTIONNER UNE IMAGE SVP!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            } else {
                //creation d'une personne
                Client cli = new Client(nom, prenoms,contact, genre, ic);
                //ajout de la personne a la liste
                file.ajouter(cli);
                //vider les champs
                vider();
                //actualiser la liste
                charge();
                JOptionPane.showMessageDialog(this, "ENREGISTREMENT EFFECTUE AVEC SUCCES!!!", "ENREGISTREMENT", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnAjouterActionPerformed

    private void lblImagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImagesMouseClicked

    private void List_enregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_enregMouseClicked
        position=List_enreg.getSelectedRow();
        c=file.client.get(position);
        affichage(c);
    }//GEN-LAST:event_List_enregMouseClicked

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        JFileChooser jc = new JFileChooser();

        //ouverture de la boite en mode selection
        int a = jc.showOpenDialog(this);

        //si l'utilisateur a selectionné un fichier
        if (a == JFileChooser.APPROVE_OPTION) {
            //    recuperation du chemin de fichier
            String chemin = jc.getSelectedFile().getAbsolutePath();
            //creation d'une ImageIcon a partir d'un fichier
            ic = new ImageIcon(chemin);
            //redimensionnement de l'image par rapport a la zone d'affichage
            ic = new ImageIcon(ic.getImage().getScaledInstance(lblImages.getWidth(), lblImages.getHeight(), Image.SCALE_DEFAULT));
            //affichage de l'image dans la zone d'affichage
            lblImages.setIcon(ic);
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        vision(true);
        vider();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int a=JOptionPane.showConfirmDialog(this, "VOULEZ VOUS VRAIMENT SUPPRIMER CE CLIENT?????? ","SUPPRESSION",JOptionPane.OK_CANCEL_OPTION);

        if(a==JOptionPane.OK_OPTION){
            file.supprimer(position);
            charge();
            vider();
            vision(true);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String nom=txtNom.getText().trim();
        String prenom= txtPrenom.getText().trim();
        String contact=txtContact.getText().trim();
        String genre = cboGenre.getSelectedItem().toString();

        if (nom.length() == 0) {
            JOptionPane.showMessageDialog(this, "VEUILLEZ SAISIR VOTRE NOM SVP!", "ERROR", JOptionPane.ERROR_MESSAGE);
            //          recuperation du curseur
            txtNom.requestFocus();
        } else if (prenom.length() == 0) {
            JOptionPane.showMessageDialog(this, "VEUILLEZ SAISIR VOTRE PRENOM(S) SVP!", "ERROR", JOptionPane.ERROR_MESSAGE);
            //          recuperation du curseur
            txtPrenom.requestFocus();

        }else{
            if (ic == null) {
                JOptionPane.showMessageDialog(this, "VEUILLEZ SELECTIONNER UNE IMAGE SVP!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                //-----------------------------
            } else {
                Client c = new Client(nom, prenom,contact,genre, ic);

                file.modifier(c,position);
                vider();
                vision(true);
                charge();
                JOptionPane.showMessageDialog(this, "ENREGISTREMENT EFFECTUE AVEC SUCCES!!!", "ENREGISTREMENT", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String codde=JOptionPane.showInputDialog("VEUILEZ SAISIR VOTRE CODE");

        int a=file.rechercher(codde);
        if(a==-1){
            JOptionPane.showMessageDialog(this, "DESOLE CE CODE N'EXISTE PAS DANS LA BASE DE DONNEE", "RECHERCHE", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            position=a;
            c=file.client.get(a);
            affichage(c);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cboGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGenreActionPerformed

    private void lblImage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImage2MouseClicked

    private void cbo_jour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_jour2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_jour2ActionPerformed

    private void btnSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectMouseClicked

    private void btnSelcet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelcet2ActionPerformed
        JFileChooser jcc = new JFileChooser();

        //ouverture de la boite en mode selection
        int a = jcc.showOpenDialog(this);

        //si l'utilisateur a selectionné un fichier
        if (a == JFileChooser.APPROVE_OPTION) {
            //    recuperation du chemin de fichier
            String chemin = jcc.getSelectedFile().getAbsolutePath();
            //creation d'une ImageIcon a partir d'un fichier
            ic2 = new ImageIcon(chemin);
            //redimensionnement de l'image par rapport a la zone d'affichage
            ic2 = new ImageIcon(ic2.getImage().getScaledInstance(lblImage2.getWidth(), lblImage2.getHeight(), Image.SCALE_DEFAULT));
            //affichage de l'image dans la zone d'affichage
            lblImage2.setIcon(ic2);
        }
    }//GEN-LAST:event_btnSelcet2ActionPerformed

    private void List_enregL_RMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_enregL_RMouseClicked
       
    }//GEN-LAST:event_List_enregL_RMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_auto_pressing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_auto_pressing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_auto_pressing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_auto_pressing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_auto_pressing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAjouter;
    private javax.swing.JTable List_enreg;
    private javax.swing.JTable List_enregL_R;
    private javax.swing.JTable List_enreg_rep;
    private javax.swing.JButton btnAnnuler2;
    private javax.swing.JButton btnAnnuler3;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnModif2;
    private javax.swing.JButton btnModifier3;
    private javax.swing.JButton btnRepasser;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelcet2;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnSupprimer2;
    private javax.swing.JButton btnSupprimer3;
    private javax.swing.JButton btn_laver_repasser;
    private javax.swing.JComboBox<String> cboGenre;
    private javax.swing.JComboBox<String> cbo_annee;
    private javax.swing.JComboBox<String> cbo_annee1;
    private javax.swing.JComboBox<String> cbo_jour1;
    private javax.swing.JComboBox<String> cbo_jour2;
    private javax.swing.JComboBox<String> cbo_mois;
    private javax.swing.JComboBox<String> cbo_mois2;
    private javax.swing.JComboBox<String> cbo_vetement;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbConct;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImages;
    private javax.swing.JTextField txtCode1;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables
}
